### PR TITLE
feat(STONEINTG-811): update kustomize path

### PR DESCRIPTION
**Pull request by MartinBasti**
Paths for staging and production overlay changed

### CODE REVIEW

**Comment by MartinBasti** [comment]
Triggered by: https://github.com/redhat-appstudio/infra-deployments/pull/3317

**Review by dirgim — APPROVED** [review]
LGTM

**Review by kasemAlem — APPROVED** [review]

**Comment by dirgim** [comment]
This should wait for https://github.com/redhat-appstudio/infra-deployments/pull/3317 before merging if I understand correctly.

**Comment by MartinBasti** [comment]
> This should wait for [redhat-appstudio/infra-deployments#3317](https://github.com/redhat-appstudio/infra-deployments/pull/3317) before merging if I understand correctly.

yes

**Review by dirgim — APPROVED** [review]
LGTM after the related changes merge

**Pull request merged**
