### PR TITLE
feat(STONEINTG-682): add promote-overlay.sh

### PR DESCRIPTION
**Pull request by hongweiliu17**
* copy promote-overlay.sh from release-service-utils
* The workflow for python is kept in case we need it later

Note: we may update the screenshot once we use it to create integration-service promotion PR

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
It misses license.
Also, if this is the exactly the same script as used for release-service, why we don't just work with them to parametrize repo-url and make it a universal script for all repos?

**Comment by MartinBasti** [comment]
release-service-utils doesn't have OSS license either, so technically this is copyright infringement

**Comment by hongweiliu17** [comment]
> It misses license. Also, if this is the exactly the same script as used for release-service, why we don't just work with them to parametrize repo-url and make it a universal script for all repos?

Good question, I thought to parameterize them, but I feel we have to remember these parameters.
I also thought we can add a manual github workflow to get the `revision` from staging.yaml and update the production.yaml.
Anyway, we can improve it later.

**Comment by hongweiliu17** [comment]
> release-service-utils doesn't have OSS license either, so technically this is copyright infringement

LICENSE file is added.

**Comment by MartinBasti** [comment]
> release-service-utils doesn't have OSS license either, so technically this is copyright infringement

Solved, repo updated licensing

**Review by MartinBasti — APPROVED** [review]

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
